fizzbuzz =require("hello")
describe("fizzbuzz", function()
        it("should be 1 when 1", function()
            assert.same("1",fizzbuzz.echo(1))
        end)
        it("should be 2 when 2", function()
            assert.same("2",fizzbuzz.echo(2))
        end)
        it("should be fizz when 3", function()
            assert.same("fizz",fizzbuzz.echo(3))
        end)
        it("should be 4 when 4", function()
            assert.same("4",fizzbuzz.echo(4))
        end)
        it("should be buzz when 5", function()
            assert.same("buzz",fizzbuzz.echo(5))
        end)
        it("should be fizz when 6", function()
            assert.same("fizz",fizzbuzz.echo(6))
        end)
        it("should be fizz when 9", function()
            assert.same("fizz",fizzbuzz.echo(9))
        end)
        it("should be fizz when 10", function()
            assert.same("buzz",fizzbuzz.echo(10))
        end)
        it("should be fizzbuzz when 15", function()
            assert.same("fizzbuzz",fizzbuzz.echo(15))
        end)
end)
