tenis = require("tenis")
describe("Tenis", function()
    describe("playerA Win", function()
        it("should Love-Love when game start", function()
            score = tenis.start()
            assert.same("Love-Love",score)
        end)
        it("should 15-Love when player a get score", function()
            score = tenis.playerA.getScore()
            assert.same("15-Love",score)
        end)
        it("should 30-Love when player a get score 2 times", function()
            score = tenis.playerA.getScore()
            assert.same("30-Love",score)
        end)
        it("should 40-Love when player a get score 3 times", function()
            score = tenis.playerA.getScore()
            assert.same("40-Love",score)
        end)
        it("should Player A Win! when player a get score while they are 40 scored", function()
            score = tenis.playerA.getScore()
            assert.same("Player A Win!",score)
        end)
    end)

    describe("playerB Win", function()
        it("should Love-Love when game start", function()
            score = tenis.start()
            assert.same("Love-Love",score)
        end)
        it("should Love-15 when player a get score", function()
            score = tenis.playerB.getScore()
            assert.same("Love-15",score)
        end)
        it("should Love-30 when player a get score 2 times", function()
            score = tenis.playerB.getScore()
            assert.same("Love-30",score)
        end)
        it("should Love-40 when player a get score 3 times", function()
            score = tenis.playerB.getScore()
            assert.same("Love-40",score)
        end)
        it("should Player B Win! when player b get score while they are 40 scored", function()
            score = tenis.playerB.getScore()
            assert.same("Player B Win!",score)
        end)
    end)

end)
